
//Q)) CREATE A CLASS STUDENT WHICH CONTAINS THE FOLLOWING DATA MEMBERS 1) STUDENT NAME 2) AGE 3) ROLL NUMBER.
//CREATE TWO FUNCTIONS ENTER AND DISPLAY
//ENTER TAKES THE INPUT FROM USER 
//DISPLAY DISPLAYS THE STUDENT DETAILS
//CREATE A CLASS TEST WHICH IS DERIVED FROM CLASS STUDENT 
//TEST CLASS CONTAINS FOLLOWING DATA MEMBERS 1) MARKS IN FOCP 2)PHYSICS 3) CHEMISTRY
//CREATE TWO FUNCTIONS CALCULATE AVERAGE AND DISPLAY AVERAGE MARKS
//CALCULATE AVERAGE MARKS TAKE THE INPUT FROM USER AND CALCULATE THE AVERAGE MARKS
//DISPLAY AVERAGE DISPLAYS THE AVERAGE MARKS
//IN THE MAIN FUNCTION CREATE AN OBJECT OF DERIVED CLASS AND ACCESS ALL THE PUBLIC DATA OF BASE CLASS AND DERIVED CLASS

#include <iostream>
using namespace std;

class  Student{
    public :
    
}